### ISSUE TITLE
Could this be project be run using a USB Host Shield and Arduino Leonardo

### ISSUE THREAD

**Issue by justcallmekoko** [RedBulletTooling/KEYVILBOARD#8]
I am trying to get more familiar with this project and USB in general. I understand the USB host IC you are using is allowing serial communication between it and the atmega32u4 so you can configure baud rates and such but there are no longer any breakout boards available that use the USB host IC used in the keyvilboard. Would it be possible to run this project using an Arduino Leonardo and a USB Host Shield?

**Comment by RedBulletTooling** [comment]
Hi,

Sorry for this very late response... For some freaking reason we didn't receive a notification via e-mail from github. Oh well, it's turned on now...

Regarding your question; It wouldn't be possible, or at least not easily. You could try to change our code base and make it fit your usb host shield, but you're better of using the code base of Spacehuhn. Spacehuhn already uses the usb host shield you are most likely referring to. We use another USB host that we found to be more easy to work with and came out better in the results during our testing fase.

Please let us know if you have any other questions by opening this issues again :).
